FROM golang:1.25.10-bookworm

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        ca-certificates \
        curl \
        gcc \
        make \
        maven \
        openjdk-17-jdk-headless \
        postgresql-client \
        python3 \
        python3-build \
        python3-pip \
        python3-setuptools \
        python3-venv \
        python3-wheel \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        python3-six \
        ripgrep \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
